version: "2.0"
services:
  mongo:
    image: mongo:3.2.4
    ports:
    - 27017:27017
    command: --smallfiles
    
  #mongo-init:
  #  build: ./mongo-init
  #  links:
  #    - mongo
      
  #mongo-client:
  #  image: mongoclient/mongoclient
  #  ports:
  #  - 3030:3000
  #  environment:
  #    - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
  #  links:
  #    - mongo
    
# APP  ***************************************************************************************
  spring-boot-mongo-docker:
    image: reservations:1
    ports:
    - 9090:9090
    links:
    - mongo
#    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar app.jar"
    entrypoint: "java -Dspring.profiles.active=docker -jar ./app.jar"
    depends_on:
    - mongo 
    
    

