apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reservations-api
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: reservations-api
    spec:
      containers:
      - name: reservations-api
        image: reservations:1
        ports: 
        - containerPort: 80
        - containerPort: 443
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
---

apiVersion: v1
kind: Service
metadata:
  name: reservations-api
spec:
  selector:
    app: reservations-api
  ports:
  - name: http
    port: 9090
  type: LoadBalancer
  